repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.9.3
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black
        language_version: python3
        exclude: migrations
  - repo: https://github.com/pycqa/flake8
    rev: '4.0.1'
    hooks:
    -   id: flake8
        name: flake8
        entry: bash -c 'git diff --staged -- "$@" | flake8 --diff' --

