name: Pull Request

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    test:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        name: Unit Tests

        steps:
            - name: Cloning repo
              uses: actions/checkout@v4

            - name: Set up Rye
              uses: sksat/setup-rye@v0.20.0

            - name: Run Tests
              run: rye sync && rye test
