name: Pull Request

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    test:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        name: Unit Tests and Linting
        env:
            FLAGSMITH_API_URL: https://api.flagsmith.com/api/v1
            FLAGSMITH_API_TOKEN: test_token
            ENVIRONMENT_API_KEYS: placeholder_key1

        steps:
            - name: Cloning repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: pyproject.toml

            - name: Check linting
              uses: pre-commit/action@v3.0.1

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt -r requirements-dev.txt

            - name: Run Tests
              run: pytest -p no:warnings
