name: Pull Request

on:
    push:
        branches:
            - main #todo - remove
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    test:
        if: github.event.pull_request.draft == false
        runs-on: ubuntu-latest
        name: Unit Tests and Linting
        env:
            FLAGSMITH_API_URL: https://api.flagsmith.com/api/v1
            FLAGSMITH_API_TOKEN: test_token
            ENVIRONMENT_API_KEYS: placeholder_key1

        strategy:
            max-parallel: 4
            matrix:
                python-version: ["3.10"]

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Cache pip download
              uses: syphar/restore-pip-download-cache@v1

            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt -r requirements-dev.txt

            - name: Check black formatting
              run: black --check .

            - name: Check flake8 linting
              run: flake8 --config=.flake8 .

            - name: Check isort imports
              run: isort --check .

            - name: Run Tests
              run: pytest -p no:warnings
