name: Deploy SSE to Production ECS

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - ".github/**"
            - 'infrastructure/aws/production/**'
jobs:
    deploy-production-ecs:
        runs-on: ubuntu-latest
        name: Deploy SSE to Production ECS
        environment: production

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Deploy SSE to Production
              uses: ./.github/actions/sse-deploy-ecs
              with:
                aws_access_key_id: AKIARHES7IUAY422LL5W
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_ecs_cluster_name: flagsmith-api-cluster-eu-west-2-f0b0108
                aws_ecs_service_name:  flagsmith-sse-svc-eu-west-2-2dd73e1
                aws_ecr_repository_arn: 084060095745.dkr.ecr.eu-west-2.amazonaws.com/flagsmith-sse-ecr-27095a4
                aws_task_definitions_directory_path: infrastructure/aws/production

