name: Deploy SSE to Staging ECS

on:
    push:
        branches:
            - main
        paths:
            - "api/**"
            - ".github/**"
            - 'infrastructure/aws/staging/**'

jobs:
    deploy-staging-ecs:
        runs-on: ubuntu-latest
        name: Deploy SSE to Staging ECS
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Deploy SSE to Staging
              uses: ./.github/actions/sse-deploy-ecs
              with:
                aws_access_key_id: AKIAUM26IRCPKP5BWQSJ
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_ecs_cluster_name: flagsmith-api-cluster-eu-west-2-f241261
                aws_ecs_service_name: flagsmith-sse-svc-eu-west-2-43f7af2
                aws_ecr_repository_arn: 302456015006.dkr.ecr.eu-west-2.amazonaws.com/flagsmith-sse-ecr-fa16ac8
                aws_task_definitions_directory_path: infrastructure/aws/staging

